spring.application.name=crud
spring.datasource.url= jdbc:postgresql://localhost:5432/postgres
spring.batch.jdbc.initialize-schema=always
spring.datasource.username=postgres
spring.datasource.name=postgres
spring.datasource.password=a33571043
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=true
