spring.application.name=crud
spring.datasource.url= jdbc:postgresql://localhost:5432/product-api
spring.batch.jdbc.initialize-schema=always
spring.datasource.username=postgres
spring.datasource.name=product-api
spring.datasource.password=1642
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=true
